//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChamadaWeb.Models
{
    using ChamadaWeb.Models.ViewModels;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Chamada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chamada()
        {
            this.ChamadaPessoa = new HashSet<ChamadaPessoa>();
        }
    
        public int Id { get; set; }
        public int IdTurma { get; set; }
        public Nullable<int> IdProfessor { get; set; }
        public string NomeProfessorConvidado { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime Data { get; set; }
        public string Licao { get; set; }
        public decimal PontuacaoGeral { get; set; }
        public bool Ativa { get; set; }
        public System.DateTime DataAlteracao { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
        public virtual Turma Turma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChamadaPessoa> ChamadaPessoa { get; set; }
        public virtual ICollection<vwChamadaPessoa> vwChamadaPessoa { get; set; }
    }
}
