//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChamadaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pessoa()
        {
            this.Chamada = new HashSet<Chamada>();
            this.ChamadaPessoa = new HashSet<ChamadaPessoa>();
            this.TurmaPessoa = new HashSet<TurmaPessoa>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string RG { get; set; }
        public Nullable<decimal> Pontuacao { get; set; }
        public bool IsProfessor { get; set; }
        public System.DateTime DataAlteracao { get; set; }
        public string Senha { get; set; }
        public bool IsSuperintendente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chamada> Chamada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChamadaPessoa> ChamadaPessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TurmaPessoa> TurmaPessoa { get; set; }
    }
}
