//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChamadaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string RG { get; set; }
        public Nullable<decimal> Pontuacao { get; set; }
        public bool IsProfessor { get; set; }
        public System.DateTime DataAlteracao { get; set; }
        public string Senha { get; set; }
        public bool IsSuperintendente { get; set; }
    }
}
