//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChamadaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurmaPessoa
    {
        public int Id { get; set; }
        public int IdTurma { get; set; }
        public int IdPessoa { get; set; }
        public decimal Pontuacao { get; set; }
        public System.DateTime DataAlteracao { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
        public virtual Turma Turma { get; set; }
    }
}
